#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /code/src/manage.py collectstatic --noinput
python /code/src/manage.py migrate
/usr/local/bin/gunicorn --pythonpath=/code/src wsgi:application --bind 0.0.0.0:5000 --chdir=/code
